### ISSUE TITLE
Credential is not authorised

### ISSUE THREAD

**Issue by amigax** [FidelLimited/fidel-android#5]
Im trying to test this to see if it works but I get "Credential is not authorised" - so I cannot tell if anythign is returned to onActivityResult, how to get aroudn this?

**Comment by ccorneliu** [comment]
Hi @amigax,

In order to test, please make sure that you set the correct `Fidel.apiKey` property. Your test key should be the one that starts with "pk_test_...". Then you can use our [test card numbers](https://github.com/FidelLimited/fidel-android#test-card-numbers) to test. You can only use test card numbers with the test API key.

Please let me know if you need more help related to this.

**Comment by amigax** [comment]
thanks!
